Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -31,17 +31,14 @@ jobs:
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
-      runs-on: ubuntu-latest
-      steps:
-      - name: Run pytest
-        run: |
-          output=$(python -m pytest -s test_hello_world.py 2>&1)
-          echo "::group::Test Output"
-          echo "$output"
-          if [[ $output == *"1 passed"* ]]; then
-            echo "Test case passed"
-          else
-            echo "Test case failed"
-            exit 1
-          fi
-          echo "::endgroup::"
+      run: |
+        output=$(python -m pytest -s test_hello_world.py 2>&1)
+        echo "::group::Test Output"
+        echo "$output"
+        if [[ $output == *"1 passed"* ]]; then
+          echo "Test case passed"
+        else
+          echo "Test case failed"
+          exit 1
+        fi
+        echo "::endgroup::"
