Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -35,4 +35,10 @@ jobs:
         output=$(python -m pytest -s test_hello_world.py 2>&1)
         echo "::group::Test Output"
         echo "$output"
+        if [[ $output == *"1 passed"* ]]; then
+          echo "Test case passed"
+        else
+          echo "Test case failed"
+          exit 1
+        fi
         echo "::endgroup::"
