Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -30,11 +30,22 @@ jobs:
         pip install xmlrunner
     - name: Lint with flake8
       run: |
-        # stop the build if there are Python syntax errors or undefined names
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
-        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Test with pytest
       run: |
-        # Redirect the "Hello, World!" output to the standard output
         python -m pytest -s
+
+  test_status:
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Check Test Status
+        run: |
+          test_output=$(python test_hello_world.py 2>&1)
+          if echo "$test_output" | grep -q "Hello, World!"; then
+            echo "Test succeeded"
+            exit 0
+          else
+            echo "Test failed"
+            exit 1
